[project]
site_name = "leafmap"
site_description = "A Python package for interactive mapping and geospatial analysis with minimal coding in a Jupyter environment"
site_author = "Qiusheng Wu"
site_url = "https://leafmap.org"
repo_url = "https://github.com/opengeos/leafmap"
copyright = "Copyright &copy; 2021 - 2026 Qiusheng Wu"

nav = [
  { "Home" = "index.md" },
  { "Book" = "https://book.leafmap.org" },
  { "Installation" = "installation.md" },
  { "Get Started" = "get-started.md" },
  { "Usage" = "notebooks/00_key_features.md" },
  { "Web App" = "https://huggingface.co/spaces/giswqs/solara-geospatial" },
  { "Tutorials" = "tutorials.md" },
  { "Contributing" = "contributing.md" },
  { "FAQ" = "faq.md" },
  { "Changelog" = "changelog.md" },
  { "YouTube Channel" = "https://youtube.com/@giswqs" },
  { "Report Issues" = "https://github.com/opengeos/leafmap/issues" },
  { "API Reference" = [
    { "basemaps module" = "basemaps.md" },
    { "bokehmap module" = "bokehmap.md" },
    { "colormaps module" = "colormaps.md" },
    { "common module" = "common.md" },
    { "deck module" = "deck.md" },
    { "deckgl module" = "deckgl.md" },
    { "download module" = "download.md" },
    { "examples module" = "examples.md" },
    { "fire module" = "fire.md" },
    { "foliumap module" = "foliumap.md" },
    { "kepler module" = "kepler.md" },
    { "maplibregl module" = "maplibregl.md" },
    { "leafmap module" = "leafmap.md" },
    { "legends module" = "legends.md" },
    { "map_widgets module" = "map_widgets.md" },
    { "osm module" = "osm.md" },
    { "pc module" = "pc.md" },
    { "plot module" = "plot.md" },
    { "plotlymap module" = "plotlymap.md" },
    { "pydeck module" = "deck.md" },
    { "stac module" = "stac.md" },
    { "terrascope module" = "terrascope.md" },
    { "toolbar module" = "toolbar.md" },
  ] },
  { "Workshops" = [
    "workshops/FOSS4G_2021.md",
    "workshops/SIGSPATIAL_2021.md",
    "workshops/YouthMappers_2021.md",
    "workshops/ICRW_2023.md",
    "workshops/EarthCube_2023.md",
    "workshops/Taiwan_2024.md",
    "workshops/HGAC_2024.md",
    "workshops/CVPR_2025.md",
    "workshops/AGU_2025.md",
  ] },
  { "MapLibre" = [
    "maplibre/overview.md",
    "maplibre/3d_buildings.md",
    "maplibre/3d_choropleth.md",
    "maplibre/3d_indoor_mapping.md",
    "maplibre/3d_pmtiles.md",
    "maplibre/3d_style.md",
    "maplibre/3d_terrain.md",
    "maplibre/add_3d_buildings.md",
    "maplibre/add_a_marker.md",
    "maplibre/add_colorbar.md",
    "maplibre/add_components.md",
    "maplibre/add_deckgl_layer.md",
    "maplibre/add_gif.md",
    "maplibre/add_html.md",
    "maplibre/add_icon.md",
    "maplibre/add_image.md",
    "maplibre/add_image_generated.md",
    "maplibre/add_labels.md",
    "maplibre/add_legend.md",
    "maplibre/add_logo.md",
    "maplibre/add_text.md",
    "maplibre/AlphaEarth.md",
    "maplibre/animate_a_line.md",
    "maplibre/animate_camera_around_point.md",
    "maplibre/animate_images.md",
    "maplibre/animate_point_along_line.md",
    "maplibre/animate_point_along_route.md",
    "maplibre/arc_layer.md",
    "maplibre/attribution_position.md",
    "maplibre/basemaps.md",
    "maplibre/center_on_symbol.md",
    "maplibre/change_building_color.md",
    "maplibre/change_case_of_labels.md",
    "maplibre/choropleth.md",
    "maplibre/cloud_optimized_geotiff.md",
    "maplibre/cluster.md",
    "maplibre/color_switcher.md",
    "maplibre/copernicus.md",
    "maplibre/countries_filter.md",
    "maplibre/create_vector.md",
    "maplibre/custom_marker.md",
    "maplibre/dashboard.md",
    "maplibre/data_driven_lines.md",
    "maplibre/disable_scroll_zoom.md",
    "maplibre/display_rich_text.md",
    "maplibre/drag_a_marker.md",
    "maplibre/draw_features.md",
    "maplibre/duckdb_layer.md",
    "maplibre/edit_vector.md",
    "maplibre/fallback_image.md",
    "maplibre/fields_of_the_world.md",
    "maplibre/fit_bounds.md",
    "maplibre/fill_pattern.md",
    "maplibre/floating_sidebar.md",
    "maplibre/fly_to.md",
    "maplibre/fly_to_options.md",
    "maplibre/fullscreen.md",
    "maplibre/geojson_layer_in_stack.md",
    "maplibre/geojson_line.md",
    "maplibre/geojson_points.md",
    "maplibre/geojson_polygon.md",
    "maplibre/geopandas.md",
    "maplibre/globe_control.md",
    "maplibre/google_earth.md",
    "maplibre/google_earth_engine.md",
    "maplibre/gps_trace.md",
    "maplibre/H3.md",
    "maplibre/heatmap_layer.md",
    "maplibre/historical_imagery.md",
    "maplibre/housing_prices.md",
    "maplibre/interactive_false.md",
    "maplibre/jump_to.md",
    "maplibre/language_switch.md",
    "maplibre/latlon_grid.md",
    "maplibre/layer_control.md",
    "maplibre/layer_groups.md",
    "maplibre/layer_manager.md",
    "maplibre/layer_styling.md",
    "maplibre/line_gradient.md",
    "maplibre/live_geojson.md",
    "maplibre/live_update_feature.md",
    "maplibre/local_geojson.md",
    "maplibre/local_raster.md",
    "maplibre/local_titiler.md",
    "maplibre/locate_user.md",
    "maplibre/map_tiles.md",
    "maplibre/mapillary.md",
    "maplibre/maptiler_styles.md",
    "maplibre/MGRS.md",
    "maplibre/mouse_position.md",
    "maplibre/multiple_geometries.md",
    "maplibre/nasa_opera.md",
    "maplibre/navigation.md",
    "maplibre/ocean_bathymetry.md",
    "maplibre/openfreemap.md",
    "maplibre/openstreetmap.md",
    "maplibre/overture.md",
    "maplibre/pmtiles.md",
    "maplibre/restrict_bounds.md",
    "maplibre/satellite_map.md",
    "maplibre/search_control.md",
    "maplibre/set_pitch_bearing.md",
    "maplibre/set_terrain.md",
    "maplibre/sidebar.md",
    "maplibre/similarity_search.md",
    "maplibre/stac.md",
    "maplibre/time_slider.md",
    "maplibre/to_html.md",
    "maplibre/variable_label_placement.md",
    "maplibre/variable_offset_label_placement.md",
    "maplibre/vector_tile.md",
    "maplibre/video_on_a_map.md",
    "maplibre/visualize_population_density.md",
    "maplibre/wms_source.md",
    "maplibre/wms_to_geotiff.md",
    "maplibre/zoom_to_linestring.md",
  ] },
  { "Notebooks" = [
    "notebooks/00_key_features.md",
    "notebooks/01_leafmap_intro.md",
    "notebooks/02_using_basemaps.md",
    "notebooks/03_cog_stac.md",
    "notebooks/04_cog_mosaic.md",
    "notebooks/05_load_raster.md",
    "notebooks/06_legend.md",
    "notebooks/07_colorbar.md",
    "notebooks/08_whitebox.md",
    "notebooks/09_csv_to_points.md",
    "notebooks/10_add_vector.md",
    "notebooks/11_linked_maps.md",
    "notebooks/12_split_map.md",
    "notebooks/13_geopandas.md",
    "notebooks/14_postgis.md",
    "notebooks/15_openstreetmap.md",
    "notebooks/16_heremap.md",
    "notebooks/17_vector_tile_layer.md",
    "notebooks/18_point_layer.md",
    "notebooks/19_map_to_html.md",
    "notebooks/20_planet_imagery.md",
    "notebooks/21_ts_inspector.md",
    "notebooks/22_time_slider.md",
    "notebooks/23_colormaps.md",
    "notebooks/24_heatmap.md",
    "notebooks/25_map_title.md",
    "notebooks/26_kepler_gl.md",
    "notebooks/27_basemap_gallery.md",
    "notebooks/28_publish_map.md",
    "notebooks/29_pydeck.md",
    "notebooks/30_census_data.md",
    "notebooks/31_search_basemaps.md",
    "notebooks/32_local_tile.md",
    "notebooks/33_image_overlay.md",
    "notebooks/34_add_points_from_xy.md",
    "notebooks/35_circle_markers.md",
    "notebooks/36_add_labels.md",
    "notebooks/37_planetary_computer.md",
    "notebooks/38_plotly.md",
    "notebooks/39_inspector_tool.md",
    "notebooks/40_plotly_gui.md",
    "notebooks/41_raster_gui.md",
    "notebooks/42_create_cog.md",
    "notebooks/43_search_control.md",
    "notebooks/44_attribute_table.md",
    "notebooks/45_create_vector.md",
    "notebooks/46_edit_vector.md",
    "notebooks/47_numpy_to_cog.md",
    "notebooks/48_lidar.md",
    "notebooks/49_split_control.md",
    "notebooks/50_marker_cluster.md",
    "notebooks/51_clip_image.md",
    "notebooks/52_netcdf.md",
    "notebooks/53_choropleth.md",
    "notebooks/54_plot_raster.md",
    "notebooks/55_lidar.md",
    "notebooks/56_download_ned.md",
    "notebooks/57_national_map.md",
    "notebooks/58_bokeh.md",
    "notebooks/59_create_legend.md",
    "notebooks/60_add_widget.md",
    "notebooks/61_vector_to_gif.md",
    "notebooks/62_folium_colorbar.md",
    "notebooks/63_arcgis.md",
    "notebooks/64_stac_search.md",
    "notebooks/65_sagemaker.md",
    "notebooks/66_gradio.md",
    "notebooks/67_maxar_open_data.md",
    "notebooks/68_openaerialmap.md",
    "notebooks/69_turkey_earthquake.md",
    "notebooks/70_zonal_stats.md",
    "notebooks/71_aws_s3.md",
    "notebooks/72_timelapse.md",
    "notebooks/73_custom_stac.md",
    "notebooks/74_map_tiles_to_geotiff.md",
    "notebooks/75_segment_anything.md",
    "notebooks/76_image_comparison.md",
    "notebooks/77_split_raster.md",
    "notebooks/78_read_raster.md",
    "notebooks/79_timeseries.md",
    "notebooks/80_solar.md",
    "notebooks/81_buildings.md",
    "notebooks/82_pmtiles.md",
    "notebooks/83_vector_viz.md",
    "notebooks/84_read_parquet.md",
    "notebooks/85_gedi.md",
    "notebooks/86_add_markers.md",
    "notebooks/87_actinia.md",
    "notebooks/88_nasa_earth_data.md",
    "notebooks/89_image_array_viz.md",
    "notebooks/90_pixel_inspector.md",
    "notebooks/91_raster_viz_gui.md",
    "notebooks/92_maplibre.md",
    "notebooks/93_maplibre_pmtiles.md",
    "notebooks/94_mapbox.md",
    "notebooks/95_edit_vector.md",
    "notebooks/96_batch_edit_vector.md",
    "notebooks/97_overture_data.md",
    "notebooks/98_watershed.md",
    "notebooks/99_wetlands.md",
    "notebooks/100_nlcd.md",
    "notebooks/101_nasa_opera.md",
    "notebooks/102_fused.md",
    "notebooks/103_raster_colormap.md",
    "notebooks/104_point_style.md",
    "notebooks/105_vector_time_slider.md",
    "notebooks/106_aws_s3.md",
    "notebooks/107_copernicus.md",
    "notebooks/108_add_geotiff.md",
    "notebooks/109_local_titiler.md",
    "notebooks/110_polars.md",
    "notebooks/111_zarr.md",
    "notebooks/112_quackosm.md",
    "notebooks/113_titiler_cmr.md",
    "notebooks/114_nasa_fire.md",
    "notebooks/115_terrascope.md",
    "notebooks/116_hls_nasa_earthdata.md",
  ] },
]

[project.theme]
logo = "assets/logo.png"
favicon = "assets/favicon.png"
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.instant",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to light mode"

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_heading = true
show_source = false

[project.extra.analytics]
provider = "google"
property = "G-B1C88N45QG"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.meta]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.highlight]
linenums = true
[project.markdown_extensions.toc]
permalink = true
