[project]
site_name = "leafmap"
site_description = "A Python package for interactive mapping and geospatial analysis with minimal coding in a Jupyter environment"
site_author = "Qiusheng Wu"
site_url = "https://leafmap.org"
repo_url = "https://github.com/opengeos/leafmap"
copyright = "Copyright &copy; 2021 - 2026 Qiusheng Wu"

nav = [
  { "Home" = "index.md" },
  { "Book" = "https://book.leafmap.org" },
  { "Installation" = "installation.md" },
  { "Get Started" = "get-started.md" },
  { "Usage" = "notebooks/00_key_features.md" },
  { "Web App" = "https://huggingface.co/spaces/giswqs/solara-geospatial" },
  { "Tutorials" = "tutorials.md" },
  { "Contributing" = "contributing.md" },
  { "FAQ" = "faq.md" },
  { "Changelog" = "changelog.md" },
  { "YouTube Channel" = "https://youtube.com/@giswqs" },
  { "Report Issues" = "https://github.com/opengeos/leafmap/issues" },
  { "API Reference" = [
    { "basemaps module" = "basemaps.md" },
    { "bokehmap module" = "bokehmap.md" },
    { "colormaps module" = "colormaps.md" },
    { "common module" = "common.md" },
    { "deck module" = "deck.md" },
    { "deckgl module" = "deckgl.md" },
    { "download module" = "download.md" },
    { "examples module" = "examples.md" },
    { "fire module" = "fire.md" },
    { "foliumap module" = "foliumap.md" },
    { "kepler module" = "kepler.md" },
    { "maplibregl module" = "maplibregl.md" },
    { "leafmap module" = "leafmap.md" },
    { "legends module" = "legends.md" },
    { "map_widgets module" = "map_widgets.md" },
    { "osm module" = "osm.md" },
    { "pc module" = "pc.md" },
    { "plot module" = "plot.md" },
    { "plotlymap module" = "plotlymap.md" },
    { "pydeck module" = "deck.md" },
    { "stac module" = "stac.md" },
    { "terrascope module" = "terrascope.md" },
    { "toolbar module" = "toolbar.md" },
  ] },
  { "Workshops" = [
    { "FOSS4G_2021" = "workshops/FOSS4G_2021.md" },
    { "SIGSPATIAL_2021" = "workshops/SIGSPATIAL_2021.md" },
    { "YouthMappers_2021" = "workshops/YouthMappers_2021.md" },
    { "ICRW_2023" = "workshops/ICRW_2023.md" },
    { "EarthCube_2023" = "workshops/EarthCube_2023.md" },
    { "Taiwan_2024" = "workshops/Taiwan_2024.md" },
    { "HGAC_2024" = "workshops/HGAC_2024.md" },
    { "CVPR_2025" = "workshops/CVPR_2025.md" },
    { "AGU_2025" = "workshops/AGU_2025.md" },
  ] },
  { "MapLibre" = [
    { "overview" = "maplibre/overview.md" },
    { "3d_buildings" = "maplibre/3d_buildings.md" },
    { "3d_choropleth" = "maplibre/3d_choropleth.md" },
    { "3d_indoor_mapping" = "maplibre/3d_indoor_mapping.md" },
    { "3d_pmtiles" = "maplibre/3d_pmtiles.md" },
    { "3d_style" = "maplibre/3d_style.md" },
    { "3d_terrain" = "maplibre/3d_terrain.md" },
    { "add_3d_buildings" = "maplibre/add_3d_buildings.md" },
    { "add_a_marker" = "maplibre/add_a_marker.md" },
    { "add_colorbar" = "maplibre/add_colorbar.md" },
    { "add_components" = "maplibre/add_components.md" },
    { "add_deckgl_layer" = "maplibre/add_deckgl_layer.md" },
    { "add_gif" = "maplibre/add_gif.md" },
    { "add_html" = "maplibre/add_html.md" },
    { "add_icon" = "maplibre/add_icon.md" },
    { "add_image" = "maplibre/add_image.md" },
    { "add_image_generated" = "maplibre/add_image_generated.md" },
    { "add_labels" = "maplibre/add_labels.md" },
    { "add_legend" = "maplibre/add_legend.md" },
    { "add_logo" = "maplibre/add_logo.md" },
    { "add_text" = "maplibre/add_text.md" },
    { "AlphaEarth" = "maplibre/AlphaEarth.md" },
    { "animate_a_line" = "maplibre/animate_a_line.md" },
    { "animate_camera_around_point" = "maplibre/animate_camera_around_point.md" },
    { "animate_images" = "maplibre/animate_images.md" },
    { "animate_point_along_line" = "maplibre/animate_point_along_line.md" },
    { "animate_point_along_route" = "maplibre/animate_point_along_route.md" },
    { "arc_layer" = "maplibre/arc_layer.md" },
    { "attribution_position" = "maplibre/attribution_position.md" },
    { "basemaps" = "maplibre/basemaps.md" },
    { "center_on_symbol" = "maplibre/center_on_symbol.md" },
    { "change_building_color" = "maplibre/change_building_color.md" },
    { "change_case_of_labels" = "maplibre/change_case_of_labels.md" },
    { "choropleth" = "maplibre/choropleth.md" },
    { "cloud_optimized_geotiff" = "maplibre/cloud_optimized_geotiff.md" },
    { "cluster" = "maplibre/cluster.md" },
    { "color_switcher" = "maplibre/color_switcher.md" },
    { "copernicus" = "maplibre/copernicus.md" },
    { "countries_filter" = "maplibre/countries_filter.md" },
    { "create_vector" = "maplibre/create_vector.md" },
    { "custom_marker" = "maplibre/custom_marker.md" },
    { "dashboard" = "maplibre/dashboard.md" },
    { "data_driven_lines" = "maplibre/data_driven_lines.md" },
    { "disable_scroll_zoom" = "maplibre/disable_scroll_zoom.md" },
    { "display_rich_text" = "maplibre/display_rich_text.md" },
    { "drag_a_marker" = "maplibre/drag_a_marker.md" },
    { "draw_features" = "maplibre/draw_features.md" },
    { "duckdb_layer" = "maplibre/duckdb_layer.md" },
    { "edit_vector" = "maplibre/edit_vector.md" },
    { "fallback_image" = "maplibre/fallback_image.md" },
    { "fields_of_the_world" = "maplibre/fields_of_the_world.md" },
    { "fit_bounds" = "maplibre/fit_bounds.md" },
    { "fill_pattern" = "maplibre/fill_pattern.md" },
    { "floating_sidebar" = "maplibre/floating_sidebar.md" },
    { "fly_to" = "maplibre/fly_to.md" },
    { "fly_to_options" = "maplibre/fly_to_options.md" },
    { "fullscreen" = "maplibre/fullscreen.md" },
    { "geojson_layer_in_stack" = "maplibre/geojson_layer_in_stack.md" },
    { "geojson_line" = "maplibre/geojson_line.md" },
    { "geojson_points" = "maplibre/geojson_points.md" },
    { "geojson_polygon" = "maplibre/geojson_polygon.md" },
    { "geopandas" = "maplibre/geopandas.md" },
    { "globe_control" = "maplibre/globe_control.md" },
    { "google_earth" = "maplibre/google_earth.md" },
    { "google_earth_engine" = "maplibre/google_earth_engine.md" },
    { "gps_trace" = "maplibre/gps_trace.md" },
    { "H3" = "maplibre/H3.md" },
    { "heatmap_layer" = "maplibre/heatmap_layer.md" },
    { "historical_imagery" = "maplibre/historical_imagery.md" },
    { "housing_prices" = "maplibre/housing_prices.md" },
    { "interactive_false" = "maplibre/interactive_false.md" },
    { "jump_to" = "maplibre/jump_to.md" },
    { "language_switch" = "maplibre/language_switch.md" },
    { "latlon_grid" = "maplibre/latlon_grid.md" },
    { "layer_control" = "maplibre/layer_control.md" },
    { "layer_groups" = "maplibre/layer_groups.md" },
    { "layer_manager" = "maplibre/layer_manager.md" },
    { "layer_styling" = "maplibre/layer_styling.md" },
    { "line_gradient" = "maplibre/line_gradient.md" },
    { "live_geojson" = "maplibre/live_geojson.md" },
    { "live_update_feature" = "maplibre/live_update_feature.md" },
    { "local_geojson" = "maplibre/local_geojson.md" },
    { "local_raster" = "maplibre/local_raster.md" },
    { "local_titiler" = "maplibre/local_titiler.md" },
    { "locate_user" = "maplibre/locate_user.md" },
    { "map_tiles" = "maplibre/map_tiles.md" },
    { "mapillary" = "maplibre/mapillary.md" },
    { "maptiler_styles" = "maplibre/maptiler_styles.md" },
    { "MGRS" = "maplibre/MGRS.md" },
    { "mouse_position" = "maplibre/mouse_position.md" },
    { "multiple_geometries" = "maplibre/multiple_geometries.md" },
    { "nasa_opera" = "maplibre/nasa_opera.md" },
    { "navigation" = "maplibre/navigation.md" },
    { "ocean_bathymetry" = "maplibre/ocean_bathymetry.md" },
    { "openfreemap" = "maplibre/openfreemap.md" },
    { "openstreetmap" = "maplibre/openstreetmap.md" },
    { "overture" = "maplibre/overture.md" },
    { "pmtiles" = "maplibre/pmtiles.md" },
    { "restrict_bounds" = "maplibre/restrict_bounds.md" },
    { "satellite_map" = "maplibre/satellite_map.md" },
    { "search_control" = "maplibre/search_control.md" },
    { "set_pitch_bearing" = "maplibre/set_pitch_bearing.md" },
    { "set_terrain" = "maplibre/set_terrain.md" },
    { "sidebar" = "maplibre/sidebar.md" },
    { "similarity_search" = "maplibre/similarity_search.md" },
    { "stac" = "maplibre/stac.md" },
    { "time_slider" = "maplibre/time_slider.md" },
    { "to_html" = "maplibre/to_html.md" },
    { "variable_label_placement" = "maplibre/variable_label_placement.md" },
    { "variable_offset_label_placement" = "maplibre/variable_offset_label_placement.md" },
    { "vector_tile" = "maplibre/vector_tile.md" },
    { "video_on_a_map" = "maplibre/video_on_a_map.md" },
    { "visualize_population_density" = "maplibre/visualize_population_density.md" },
    { "wms_source" = "maplibre/wms_source.md" },
    { "wms_to_geotiff" = "maplibre/wms_to_geotiff.md" },
    { "zoom_to_linestring" = "maplibre/zoom_to_linestring.md" },
  ] },
  { "Notebooks" = [
    { "00_key_features" = "notebooks/00_key_features.md" },
    { "01_leafmap_intro" = "notebooks/01_leafmap_intro.md" },
    { "02_using_basemaps" = "notebooks/02_using_basemaps.md" },
    { "03_cog_stac" = "notebooks/03_cog_stac.md" },
    { "04_cog_mosaic" = "notebooks/04_cog_mosaic.md" },
    { "05_load_raster" = "notebooks/05_load_raster.md" },
    { "06_legend" = "notebooks/06_legend.md" },
    { "07_colorbar" = "notebooks/07_colorbar.md" },
    { "08_whitebox" = "notebooks/08_whitebox.md" },
    { "09_csv_to_points" = "notebooks/09_csv_to_points.md" },
    { "10_add_vector" = "notebooks/10_add_vector.md" },
    { "11_linked_maps" = "notebooks/11_linked_maps.md" },
    { "12_split_map" = "notebooks/12_split_map.md" },
    { "13_geopandas" = "notebooks/13_geopandas.md" },
    { "14_postgis" = "notebooks/14_postgis.md" },
    { "15_openstreetmap" = "notebooks/15_openstreetmap.md" },
    { "16_heremap" = "notebooks/16_heremap.md" },
    { "17_vector_tile_layer" = "notebooks/17_vector_tile_layer.md" },
    { "18_point_layer" = "notebooks/18_point_layer.md" },
    { "19_map_to_html" = "notebooks/19_map_to_html.md" },
    { "20_planet_imagery" = "notebooks/20_planet_imagery.md" },
    { "21_ts_inspector" = "notebooks/21_ts_inspector.md" },
    { "22_time_slider" = "notebooks/22_time_slider.md" },
    { "23_colormaps" = "notebooks/23_colormaps.md" },
    { "24_heatmap" = "notebooks/24_heatmap.md" },
    { "25_map_title" = "notebooks/25_map_title.md" },
    { "26_kepler_gl" = "notebooks/26_kepler_gl.md" },
    { "27_basemap_gallery" = "notebooks/27_basemap_gallery.md" },
    { "28_publish_map" = "notebooks/28_publish_map.md" },
    { "29_pydeck" = "notebooks/29_pydeck.md" },
    { "30_census_data" = "notebooks/30_census_data.md" },
    { "31_search_basemaps" = "notebooks/31_search_basemaps.md" },
    { "32_local_tile" = "notebooks/32_local_tile.md" },
    { "33_image_overlay" = "notebooks/33_image_overlay.md" },
    { "34_add_points_from_xy" = "notebooks/34_add_points_from_xy.md" },
    { "35_circle_markers" = "notebooks/35_circle_markers.md" },
    { "36_add_labels" = "notebooks/36_add_labels.md" },
    { "37_planetary_computer" = "notebooks/37_planetary_computer.md" },
    { "38_plotly" = "notebooks/38_plotly.md" },
    { "39_inspector_tool" = "notebooks/39_inspector_tool.md" },
    { "40_plotly_gui" = "notebooks/40_plotly_gui.md" },
    { "41_raster_gui" = "notebooks/41_raster_gui.md" },
    { "42_create_cog" = "notebooks/42_create_cog.md" },
    { "43_search_control" = "notebooks/43_search_control.md" },
    { "44_attribute_table" = "notebooks/44_attribute_table.md" },
    { "45_create_vector" = "notebooks/45_create_vector.md" },
    { "46_edit_vector" = "notebooks/46_edit_vector.md" },
    { "47_numpy_to_cog" = "notebooks/47_numpy_to_cog.md" },
    { "48_lidar" = "notebooks/48_lidar.md" },
    { "49_split_control" = "notebooks/49_split_control.md" },
    { "50_marker_cluster" = "notebooks/50_marker_cluster.md" },
    { "51_clip_image" = "notebooks/51_clip_image.md" },
    { "52_netcdf" = "notebooks/52_netcdf.md" },
    { "53_choropleth" = "notebooks/53_choropleth.md" },
    { "54_plot_raster" = "notebooks/54_plot_raster.md" },
    { "55_lidar" = "notebooks/55_lidar.md" },
    { "56_download_ned" = "notebooks/56_download_ned.md" },
    { "57_national_map" = "notebooks/57_national_map.md" },
    { "58_bokeh" = "notebooks/58_bokeh.md" },
    { "59_create_legend" = "notebooks/59_create_legend.md" },
    { "60_add_widget" = "notebooks/60_add_widget.md" },
    { "61_vector_to_gif" = "notebooks/61_vector_to_gif.md" },
    { "62_folium_colorbar" = "notebooks/62_folium_colorbar.md" },
    { "63_arcgis" = "notebooks/63_arcgis.md" },
    { "64_stac_search" = "notebooks/64_stac_search.md" },
    { "65_sagemaker" = "notebooks/65_sagemaker.md" },
    { "66_gradio" = "notebooks/66_gradio.md" },
    { "67_maxar_open_data" = "notebooks/67_maxar_open_data.md" },
    { "68_openaerialmap" = "notebooks/68_openaerialmap.md" },
    { "69_turkey_earthquake" = "notebooks/69_turkey_earthquake.md" },
    { "70_zonal_stats" = "notebooks/70_zonal_stats.md" },
    { "71_aws_s3" = "notebooks/71_aws_s3.md" },
    { "72_timelapse" = "notebooks/72_timelapse.md" },
    { "73_custom_stac" = "notebooks/73_custom_stac.md" },
    { "74_map_tiles_to_geotiff" = "notebooks/74_map_tiles_to_geotiff.md" },
    { "75_segment_anything" = "notebooks/75_segment_anything.md" },
    { "76_image_comparison" = "notebooks/76_image_comparison.md" },
    { "77_split_raster" = "notebooks/77_split_raster.md" },
    { "78_read_raster" = "notebooks/78_read_raster.md" },
    { "79_timeseries" = "notebooks/79_timeseries.md" },
    { "80_solar" = "notebooks/80_solar.md" },
    { "81_buildings" = "notebooks/81_buildings.md" },
    { "82_pmtiles" = "notebooks/82_pmtiles.md" },
    { "83_vector_viz" = "notebooks/83_vector_viz.md" },
    { "84_read_parquet" = "notebooks/84_read_parquet.md" },
    { "85_gedi" = "notebooks/85_gedi.md" },
    { "86_add_markers" = "notebooks/86_add_markers.md" },
    { "87_actinia" = "notebooks/87_actinia.md" },
    { "88_nasa_earth_data" = "notebooks/88_nasa_earth_data.md" },
    { "89_image_array_viz" = "notebooks/89_image_array_viz.md" },
    { "90_pixel_inspector" = "notebooks/90_pixel_inspector.md" },
    { "91_raster_viz_gui" = "notebooks/91_raster_viz_gui.md" },
    { "92_maplibre" = "notebooks/92_maplibre.md" },
    { "93_maplibre_pmtiles" = "notebooks/93_maplibre_pmtiles.md" },
    { "94_mapbox" = "notebooks/94_mapbox.md" },
    { "95_edit_vector" = "notebooks/95_edit_vector.md" },
    { "96_batch_edit_vector" = "notebooks/96_batch_edit_vector.md" },
    { "97_overture_data" = "notebooks/97_overture_data.md" },
    { "98_watershed" = "notebooks/98_watershed.md" },
    { "99_wetlands" = "notebooks/99_wetlands.md" },
    { "100_nlcd" = "notebooks/100_nlcd.md" },
    { "101_nasa_opera" = "notebooks/101_nasa_opera.md" },
    { "102_fused" = "notebooks/102_fused.md" },
    { "103_raster_colormap" = "notebooks/103_raster_colormap.md" },
    { "104_point_style" = "notebooks/104_point_style.md" },
    { "105_vector_time_slider" = "notebooks/105_vector_time_slider.md" },
    { "106_aws_s3" = "notebooks/106_aws_s3.md" },
    { "107_copernicus" = "notebooks/107_copernicus.md" },
    { "108_add_geotiff" = "notebooks/108_add_geotiff.md" },
    { "109_local_titiler" = "notebooks/109_local_titiler.md" },
    { "110_polars" = "notebooks/110_polars.md" },
    { "111_zarr" = "notebooks/111_zarr.md" },
    { "112_quackosm" = "notebooks/112_quackosm.md" },
    { "113_titiler_cmr" = "notebooks/113_titiler_cmr.md" },
    { "114_nasa_fire" = "notebooks/114_nasa_fire.md" },
    { "115_terrascope" = "notebooks/115_terrascope.md" },
    { "116_hls_nasa_earthdata" = "notebooks/116_hls_nasa_earthdata.md" },
  ] },
]

[project.theme]
logo = "assets/logo.png"
favicon = "assets/favicon.png"
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.instant",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to light mode"

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_heading = true
show_source = false

[project.extra.analytics]
provider = "google"
property = "G-B1C88N45QG"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.meta]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.highlight]
linenums = true
[project.markdown_extensions.toc]
permalink = true
