on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    # - { os: windows-latest, py: "3.9" }
                    - { os: macOS-latest, py: "3.9" }
                    - { os: ubuntu-latest, py: "3.7" }
                    - { os: ubuntu-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.9" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v2
            - name: SETUP PYTHON
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt -r requirements_dev.txt
            - name: PKG-TEST
              run: |
                  pip install geopandas osmnx xarray_leaflet keplergl pydeck
                  python -m unittest discover tests/
              env:
                  HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
                  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
