on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    # - { os: windows-latest, py: "3.9" }
                    - { os: macOS-latest, py: "3.9" }
                    - { os: ubuntu-latest, py: "3.7" }
                    - { os: ubuntu-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.9" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v2
            - name: SETUP PYTHON
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install codespell -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: Discover typos with codespell
              run: codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs"
            - name: PKG-TEST
              run: |
                  pip install xarray_leaflet geopandas osmnx sqlalchemy psycopg2 keplergl datapane pydeck localtileserver rio-cogeo
                  python -m unittest discover tests/
              env:
                  HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
                  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
