name: Check for Large Files

on:
    pull_request:
        paths:
            - "**"

jobs:
    check-large-files:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Check for Large Files
              run: |
                  # Define the maximum file size limit in bytes (e.g., 1 MB)
                  MAX_FILE_SIZE=1000000

                  # Check for large files and list them
                  LARGE_FILES=$(find . -type f -size +$MAX_FILE_SIZE)

                  # If there are large files, fail the action and display a message
                  if [ -n "$LARGE_FILES" ]; then
                    echo "Large files found:"
                    echo "$LARGE_FILES"
                    exit 1
                  fi
