name: Check Pull Request File Size and Print Size Changes

on:
    pull_request:
        paths:
            - "**"

jobs:
    check_file_size:
        runs-on: ubuntu-latest

        steps:
            - name: Check File Size
              id: check_file_size
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Get Changed Files
              id: get_changed_files
              run: |
                  echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" >> $GITHUB_ENV
              shell: bash

            - name: Check File Size Changes and Fail if Exceeds 2MB
              id: check_size_changes
              run: |
                  for file in $changed_files; do
                    old_size=$(stat -c %s "$file")
                    git checkout ${{ github.event.before }} -- "$file"
                    new_size=$(stat -c %s "$file")
                    size_change=$(($new_size - $old_size))
                    size_change_in_mb=$(($size_change / 1000000))

                    echo "File: $file"
                    echo "Old Size: $(($old_size / 1000000)) MB"
                    echo "New Size: $(($new_size / 1000000)) MB"
                    echo "Size Change: $size_change_in_mb MB"

                    if [ $size_change_in_mb -gt 2 ]; then
                      echo "Size change exceeds 2MB limit. Failing the workflow."
                      exit 1
                    fi
                  done
              shell: bash
