on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: macOS build
jobs:
    test-macOS:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: macOS-latest, py: "3.12" }
        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v2
              with:
                  version: "0.4.12"
                  enable-cache: true

            - name: Set up Python ${{ matrix.config.py }}
              run: uv python install ${{ matrix.config.py }}

            - name: Install dependencies
              run: uv sync --python ${{ matrix.config.py }}

            - name: Install optional dependencies
              run: |
                  uv pip install --find-links https://girder.github.io/large_image_wheels gdal pyproj
                  uv pip install -r requirements_dev.txt

            - name: Test import
              run: |
                  uv run python -c "import leafmap; print('leafmap import successful')"
                  uv run python -c "from osgeo import gdal; print('gdal import successful')"
                  uv run gdalinfo --version
